# Generated by Django 6.0.6 on 2026-06-23 00:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(help_text='Dirección de email única del autor.', max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Nombre y apellido del autor.', max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Autor asociado a esta publicación.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Cuerpo de texto de la publicación.', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(help_text='Fecha y hora exactas de publicación.', verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(help_text='Etiquetas vinculadas a esta publicación.', related_name='posts', to='blog.tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Título de la publicación (mínimo 5 caracteres).', max_length=200, validators=[django.core.validators.MinLengthValidator(5, message='El título debe tener al menos 5 caracteres.')], verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Categoría para clasificar publicaciones.', max_length=30, verbose_name='Nombre de la etiqueta'),
        ),
    ]
