# Generated by Django 6.0.6 on 2026-06-23 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(help_text='Dirección de email única e irrepetible para el autor.', max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Nombre y apellido del autor de forma obligatoria.', max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Autor que redactó la publicación.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Cuerpo de texto principal del artículo.', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(help_text='Fecha y hora en la que se hace público el artículo.', verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Etiquetas vinculadas. Este campo es opcional para permitir flexibilidad.', related_name='posts', to='blog.tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Título descriptivo de la publicación (mínimo 5 caracteres).', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Palabra clave única para agrupar publicaciones.', max_length=30, unique=True, verbose_name='Nombre de la etiqueta'),
        ),
    ]
