# Generated by Django 6.0.6 on 2026-06-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tematica', models.CharField(max_length=100)),
                ('anio_estreno', models.IntegerField()),
            ],
        ),
    ]
