# Generated by Django 6.0.6 on 2026-06-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documental',
            options={'verbose_name': 'Documental', 'verbose_name_plural': 'Documentales'},
        ),
        migrations.AlterField(
            model_name='documental',
            name='anio_estreno',
            field=models.IntegerField(help_text='Año en el que la producción fue lanzada oficialmente.', verbose_name='Año de estreno'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='tematica',
            field=models.CharField(help_text='Categoría o género del documental (ej: Deportes, Historia).', max_length=100, verbose_name='Temática principal'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='titulo',
            field=models.CharField(help_text='Ingrese el nombre completo de la producción cinematográfica o serie.', max_length=200, verbose_name='Título del documental'),
        ),
    ]
