# Generated by Django 4.2.13 on 2026-06-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_documental_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='documental',
            name='anio_estreno',
            field=models.PositiveIntegerField(help_text='Año en el que la producción fue lanzada oficialmente.', verbose_name='Año de estreno'),
        ),
    ]
